// Classification of all state attributes possible
// TODO: Read / Write ergänzen
const stateAttrb: Record<string, Partial<ioBroker.StateCommon> & {factor?: number}> = {
	'actualityDuration': {
		name: '< unknown >',
		type: 'number',
		role: 'state',
		unit: '',
	},
	'energy': {
		name: 'Zählerstand Bezug Gesamt',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'kWh',
		factor: 10000000000,
	},
	'energy1': {
		name: 'Zählerstand Bezug T1',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'kWh',
		factor: 10000000000,
	},
	'energy2': {
		name: 'Zählerstand Bezug T2',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'kWh',
		factor: 10000000000,
	},
	'energy3': {
		name: 'Zählerstand Bezug T3',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'kWh',
		factor: 10000000000,
	},
	'energyOut': {
		name: 'Zählerstand Abgabe Gesammt',
		type: 'number',
		role: 'value.power.delivery',
		unit: 'kWh',
		factor: 10000000000,
	},
	'energyOut1': {
		name: 'Zählerstand Abgabe T1',
		type: 'number',
		role: 'value.power.delivery',
		unit: 'kWh',
		factor: 10000000000,
	},
	'energyOut2': {
		name: 'Zählerstand Abgabe T2',
		type: 'number',
		role: 'value.power.delivery',
		unit: 'kWh',
		factor: 10000000000,
	},
	'energyOut3': {
		name: 'Zählerstand Abgabe T3',
		type: 'number',
		role: 'value.power.delivery',
		unit: 'kWh',
		factor: 10000000000,
	},
	'energyProducer8': {
		name: 'energy Producer',
		type: 'number',
		role: 'value.power.delivery',
		unit: 'kWh',
		factor: 10000000000,
	},
	'energyProducer9': {
		name: 'energy Producer',
		type: 'number',
		role: 'value.power.delivery',
		unit: 'kWh',
		factor: 10000000000,
	},
	'energyProducer10': {
		name: 'energy Producer',
		type: 'number',
		role: 'value.power.delivery',
		unit: 'kWh',
		factor: 10000000000,
	},
	'serialNumber': {
		name: 'Serialnumber',
		type: 'number',
		role: 'state',
	},
	'lastMeasurementTime': {
		name: 'lastMeasurement Time',
		type: 'number',
		role: 'state',
	},
	'firstMeasurementTime': {
		name: 'firstMeasurementTime',
		type: 'number',
		role: 'state',
	},
	'internalMeters': {
		name: 'internal Meters',
		type: 'number',
		role: 'state',
	},
	'voltageScalingFactor': {
		name: 'voltage ScalingFactor',
		type: 'number',
		role: 'state',
	},
	'currentScalingFactor': {
		name: 'current ScalingFactor',
		type: 'number',
		role: 'state',
	},
	'scalingFactor': {
		name: 'scaling Factor',
		type: 'number',
		role: 'state',
	},
	'loadProfileType': {
		name: 'loadProfileType',
		type: 'mixed',
		role: 'state',
	},
	'measurementType': {
		name: 'measurementType',
		type: 'mixed',
		role: 'state',
	},
	'type': {
		name: 'type',
		type: 'mixed',
		role: 'state',
	},
	'administrationNumber': {
		name: 'administration Number',
		type: 'number',
		role: 'state',
	},
	'location': {
		name: 'location',
		type: 'array',
		role: 'state',
	},
	'fullSerialNumber': {
		name: 'full Serial Number',
		type: 'number',
		role: 'state',
	},
	'manufacturerId': {
		name: 'manufacturer Id',
		type: 'number',
		role: 'state',
	},
	'meterId': {
		name: 'meterId',
		type: 'number',
		role: 'state',
	},
	'power': {
		name: 'Power',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'W',
	},
	'power1': {
		name: 'Power 1',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'W',
		factor: 1000,
	},
	'power2': {
		name: 'Power 2',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'W',
		factor: 1000,
	},
	'power3': {
		name: 'Power 3',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'W',
		factor: 1000,
	},
	'Power_Consumption': {
		name: 'Power_Consumption',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'W',
		factor: 1000,
	},
	'Power_T1_Consumption': {
		name: 'Power_T1_Consumption',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'W',
		factor: 1000,
	},
	'Power_T2_Consumption': {
		name: 'Power_T2_Consumption',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'W',
		factor: 1000,
	},
	'Power_T3_Consumption': {
		name: 'Power_T3_Consumption',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'W',
		factor: 1000,
	},
	'Power_Delivery': {
		name: 'Power_Delivery',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'W',
		factor: 1000,
	},
	'Power_T1_Delivery': {
		name: 'Power_T1_Delivery',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'W',
		factor: 1000,
	},
	'Power_T2_Delivery': {
		name: 'Power_T2_Delivery',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'W',
		factor: 1000,
	},
	'Power_T3_Delivery': {
		name: 'Power_T3_Delivery',
		type: 'number',
		role: 'value.power.consumption',
		unit: 'W',
		factor: 1000,
	},
	'voltage': {
		name: 'Voltage',
		type: 'number',
		role: 'value.voltage',
		unit: 'V',
		factor: 1000,
	},
	'voltage1': {
		name: 'Voltage',
		type: 'number',
		role: 'value.voltage',
		unit: 'V',
		factor: 1000,
	},
	'voltage2': {
		name: 'Voltage',
		type: 'number',
		role: 'value.voltage',
		unit: 'V',
		factor: 1000,
	},
	'voltage3': {
		name: 'Voltage',
		type: 'number',
		role: 'value.voltage',
		unit: 'V',
		factor: 1000,
	},
	'volume': {
		name: 'Volume',
		type: 'number',
		role: 'state',
		unit: 'm3',
	},
};

export default stateAttrb;